services:
    postgres:
        image: postgres:16
        restart: always

        volumes:
            - postgres:/var/lib/postgresql
        environment:
            - POSTGRES_USER=${postgres_user}
            - POSTGRES_PASSWORD=${postgres_pass}

    backend:
        build: .
        image: backend
        command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
        ports:
            - "8080:8000"
        volumes:
            - ./backend:/home/backend
        env_file: .env

volumes:
    postgres:
